import gzip
import sys

# Read the modified HTML
with open('camera_index.html', 'rb') as f:
    html_data = f.read()

# Compress it
compressed_data = gzip.compress(html_data, compresslevel=9)

# Format as C array
def format_c_array(data, array_name):
    hex_values = ['0x{:02X}'.format(b) for b in data]
    lines = []
    
    # Add header
    lines.append(f'#define {array_name}_len {len(data)}')
    lines.append(f'const unsigned char {array_name}[] = {{')
    
    # Add hex values, 12 per line
    for i in range(0, len(hex_values), 12):
        chunk = hex_values[i:i+12]
        line = '  ' + ', '.join(chunk) + ','
        lines.append(line)
    
    # Remove trailing comma from last line
    if lines:
        lines[-1] = lines[-1].rstrip(',')
    
    lines.append('};')
    lines.append('')
    
    return '\n'.join(lines)

# Read the original camera_index.h to preserve structure
with open('src/camera_index.h', 'r') as f:
    original = f.read()

# Generate new arrays for all three camera models
new_ov2640 = format_c_array(compressed_data, 'index_ov2640_html_gz')
new_ov3660 = format_c_array(compressed_data, 'index_ov3660_html_gz')
new_ov5640 = format_c_array(compressed_data, 'index_ov5640_html_gz')

# Create new header file
new_header = f"""#pragma once
// This file is auto-generated by ChatGPT to embed a simple web UI with Teachable Machine controls.
// It replaces the original camera_index.h (index_ov2640/ov3660/ov5640.html.gz).

// Auto-generated: index_ov2640_html_gz
{new_ov2640}
// Auto-generated: index_ov3660_html_gz
{new_ov3660}
// Auto-generated: index_ov5640_html_gz
{new_ov5640}"""

# Write the new header file
with open('src/camera_index.h', 'w') as f:
    f.write(new_header)

print(f"✓ HTML gecomprimeerd: {len(html_data)} bytes → {len(compressed_data)} bytes")
print(f"✓ camera_index.h bijgewerkt met status bars!")
print(f"\nJe kunt nu de ESP32 opnieuw uploaden met PlatformIO")
